### ISSUE TITLE
Docs are a 404

### ISSUE THREAD

**Issue by GoombaProgrammer** [GoldenretriverYT/PoopWeb#1]
What is the URL of the current docs?

**Comment by GoldenretriverYT** [comment]
![image](https://user-images.githubusercontent.com/49924528/146336010-784a118e-f28f-4bde-88e8-1935f2a66d19.png)

**Comment by GoombaProgrammer** [comment]
Make it say [DO NOT EXIST YET] because people will think its an unfinished doc but that it does exist.

**Comment by GoldenretriverYT** [comment]
Apart from that, the unfinished docs are available in the [docs folder, ex. index.html](https://github.com/GoldenretriverYT/PoopWeb/blob/master/docs/index.html)

**Comment by GoldenretriverYT** [comment]
Docs now available under https://goldenretriveryt.github.io/PoopWeb/
